### ISSUE TITLE
problem with paths

### ISSUE THREAD

**Issue by Harmanz** [dicksonlaw583/jsontoolkit#2]
after loading and saving json, string "libs/new/ss/grid.xml", turns to https://i.gyazo.com/4e67faae0b30522e6c06c0761dffb9cf.png

**Comment by dicksonlaw583** [comment]
If it saves JSON like that, it's because the `json_encode()` built into the runner escapes forward slashes by default. This happens with some JSON parsers. As long as `json_load()` doesn't give you the backslashes in the decoded data structure, you shouldn't worry about it.

Please note that controlling specific behaviour of `json_encode()` and `json_decode()` is not the domain of JSON Toolkit. If a problem arises with these two functions, please bring it up with YoYo.

**Comment by Harmanz** [comment]
thank you
