### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by mmuziek** [dicksonlaw583/jsontoolkit#7]
Hello 
Just figured out that it seems that JSON_DECODE is causing a memory leak.
here is how i use it :
`var t_buffer = async_load[? "buffer"]; 
	if (t_buffer != undefined){
			
    var cmd_type = buffer_read(t_buffer, buffer_string );
	cmd_type = string_replace_all(cmd_type, "|", "");
	global.lastReceived = json_decode(cmd_type);
	cmd_type = "";
	buffer_delete(t_buffer);
	}
	`

strange enough when using this code (executed every second)  the packets are send every second to this system.
yet the memory from the app slowly starts to rise to about 1.5 Gigs then lowering down back to 500 before rising again.
Since the app starts at 200 Mb ram and when i comment out the json_decode the ram stays on 200 mb when i use the json decode again it starts to slowly rise to the 1.5 gigs (i tested it only on my pc with 32 gigs of ram) some people who use my game compained that they ran out of memory when using my app long
i got 1 example i could fully verify that he was playing about 3 hours (every second a packet that gets decoded) he ended up having a app crash with the out of memory due to the app using almost 3 gigs (he had 6 installed but all comined was too much) 

i tried searching if i could find any other thing causing this yet the global var made using the cmd_type is only used by my objects using Json_get to get the data out. thats it.
`json_get(global.lastReceived, "varc", "subvar1","subsubvar1");`
So i hope u might be able to help me :) as it kills my app when using it longer then 30 minutes for most people only the people with much more ram can handle up to 5 hours

**Comment by dicksonlaw583** [comment]
You cannot just set `global.lastReceived` away to a new map without destroying the one already there, otherwise you would get a memory leak. Do `ds_map_destroy(global.lastReceived);` before you set it away to a new map given by `json_decode`. JSON Toolkit is not involved with `json_decode` as it is built into the GM runner, not in the library.

Also, if you are using GMS 2.3+, you should be using `json_parse` with structs, which clean after themselves unlike DS maps and can be directly accessed using built-in syntax. JSON Toolkit is really only intended as legacy support, new projects have no real reason to use it.

**Comment by mmuziek** [comment]
oh that was it sorry for the question problem resolved :D!
